apiVersion: v1
kind: Pod
metadata:
  name: pod-with-nodeaffinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - ap-south-1a
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
